# Generated by Django 2.0.13 on 2019-12-14 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=200)),
                ('cou_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200)),
                ('edu_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(max_length=200)),
                ('hob_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('sex', models.CharField(max_length=1)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Personal')),
            ],
        ),
        migrations.AddField(
            model_name='hobbies',
            name='personal_h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Personal'),
        ),
        migrations.AddField(
            model_name='education',
            name='personal_e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Personal'),
        ),
        migrations.AddField(
            model_name='courses',
            name='personal_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Personal'),
        ),
    ]
