# Generated by Django 2.2.7 on 2019-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbies',
            name='hob_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='courses',
            name='cou_date',
            field=models.DateTimeField(verbose_name='finish date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_date',
            field=models.DateTimeField(verbose_name='finish date'),
        ),
    ]
